version: '3.8'
services:
  cass1:
    build: .
    depends_on:
      - jaeger
    volumes:
      - /tmp/cass-data1:/data
    command:
      - "cass"
      - "server"
      - "--node-addr"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass3:8080"
      - "--peer"
      - "http://cass4:8080"
      - "--peer"
      - "http://cass5:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "3"
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=cass
      - OTEL_SERVICE_INSTANCE_ID=cass1
      - CASS_DISABLE_TRACING=${CASS_DISABLE_TRACING:-0}

  cass2:
    build: .
    depends_on:
      - jaeger
    volumes:
      - /tmp/cass-data2:/data
    command:
      - "cass"
      - "server"
      - "--node-addr"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass3:8080"
      - "--peer"
      - "http://cass4:8080"
      - "--peer"
      - "http://cass5:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "3"
    ports:
      - "8081:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=cass
      - OTEL_SERVICE_INSTANCE_ID=cass2
      - CASS_DISABLE_TRACING=${CASS_DISABLE_TRACING:-0}

  cass3:
    build: .
    depends_on:
      - jaeger
    volumes:
      - /tmp/cass-data3:/data
    command:
      - "cass"
      - "server"
      - "--node-addr"
      - "http://cass3:8080"
      - "--peer"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass4:8080"
      - "--peer"
      - "http://cass5:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "3"
    ports:
      - "8082:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=cass
      - OTEL_SERVICE_INSTANCE_ID=cass3
      - CASS_DISABLE_TRACING=${CASS_DISABLE_TRACING:-0}

  cass4:
    build: .
    depends_on:
      - jaeger
    volumes:
      - /tmp/cass-data4:/data
    command:
      - "cass"
      - "server"
      - "--node-addr"
      - "http://cass4:8080"
      - "--peer"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass3:8080"
      - "--peer"
      - "http://cass5:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "3"
    ports:
      - "8083:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=cass
      - OTEL_SERVICE_INSTANCE_ID=cass4
      - CASS_DISABLE_TRACING=${CASS_DISABLE_TRACING:-0}

  cass5:
    build: .
    depends_on:
      - jaeger
    volumes:
      - /tmp/cass-data5:/data
    command:
      - "cass"
      - "server"
      - "--node-addr"
      - "http://cass5:8080"
      - "--peer"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass3:8080"
      - "--peer"
      - "http://cass4:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "3"
    ports:
      - "8084:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=cass
      - OTEL_SERVICE_INSTANCE_ID=cass5
      - CASS_DISABLE_TRACING=${CASS_DISABLE_TRACING:-0}

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_QUERY__METRICS_BACKEND=prometheus
      - JAEGER_QUERY__PROMETHEUS_SERVER_URL=http://prometheus:9090

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
      - ./grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./static/dashboard.json:/var/lib/grafana/dashboards/dashboard.json:ro
    ports:
      - '3000:3000'
