version: '3.8'
services:
  cass1:
    build: .
    volumes:
      - ./data1:/data
    command:
      - "cass"
      - "--node-addr"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass3:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "2"
    ports:
      - "8080:8080"

  cass2:
    build: .
    volumes:
      - ./data2:/data
    command:
      - "cass"
      - "--node-addr"
      - "http://cass2:8080"
      - "--peer"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass3:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "2"
    ports:
      - "8081:8080"

  cass3:
    build: .
    volumes:
      - ./data3:/data
    command:
      - "cass"
      - "--node-addr"
      - "http://cass3:8080"
      - "--peer"
      - "http://cass1:8080"
      - "--peer"
      - "http://cass2:8080"
      - "--data-dir"
      - "/data"
      - "--rf"
      - "2"
    ports:
      - "8082:8080"
